name = "Throw In Destruct";
description = "According to the manual, ``Attempting to throw an exception from a destructor (called in the time of script termination) causes a fatal error.``

The destructor may be called during the lifespan of the script, but it is not certain. If the exception is thrown later, the script may end up with a fatal error. 

Thus, it is recommended to avoid throwing exceptions within the ``__destruct`` method of a class.

<?php

// No exception thrown
class Bar { 
    function __construct() {
        throw new Exception('__construct');
    }

    function __destruct() {
        $this->cleanObject();
    }
}

// Potential crash
class Foo { 
    function __destruct() {
        throw new Exception('__destruct');
    }
}

?>

See also `Constructors and Destructors <https://www.php.net/manual/en/language.oop5.decon.php>`_.
";
clearphp = "";
severity = "S_MAJOR";
timetofix = "T_QUICK";
exakatSince = "0.8.4";

modifications[] = "Remove any exception thrown from a destructor"